force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Number_of_Times_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Times_Rejected__c</fullName>
    <label>Number of Times Rejected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TimesheetRejectionCounter.cls
public with sharing class TimesheetRejectionCounter {

    public static void updateTimesRejectedOnRejection(List<Timesheet__c> updatedTimesheets,
                                                        Map<Id, Timesheet__c> oldTimesheetMap) {

        for(Timesheet__c timesheet : updatedTimesheets) {
            if(timesheet.Status__c == 'Rejected' &&
                oldTimesheetMap.get(timesheet.Id).Status__c != timesheet.Status__c) {

                if(timesheet.Number_of_Times_Rejected__c == null) {
                    timesheet.Number_of_Times_Rejected__c = 0;
                }
                
                timesheet.Number_of_Times_Rejected__c = timesheet.Number_of_Times_Rejected__c + 1;
            }
        }
    }
}